#User Configuration
IMAGE_INSTALL:remove = "jesd-status"
BBMASK += ".*/meta-adi-xilinx/recipes-support/jesd-status/jesd-status_dev.bb"
KERNEL_VERSION_SANITY_SKIP = "1"
#OE_TERMINAL = "tmux"
PREFERRED_PROVIDER_virtual/kernel = "linux-xlnx"
PREFERRED_VERSION_linux-xlnx = "6.6%"

# Use PetaLinux-generated device tree + our system-user.dtsi.
# Do not use ADI reference-design device-tree override.
BBMASK += ".*/meta-adi-xilinx/recipes-bsp/device-tree/device-tree\.bbappend"
IMAGE_INSTALL:remove = "fru-tools"
BBMASK += ".*/meta-adi-xilinx/recipes-support/fru-tools/fru-tools_0\.8\.1\.5\.bb"