create_clock -period 8.138 -name rx_data_clock [get_ports rx_clk_in_p]
create_clock -period 25.000 -name adc_clk_out [get_ports adc_clk_out]
#set_property SEVERITY {Warning} [get_drc_checks BIVC-1]
set_property PACKAGE_PIN P16 [get_ports SPI0_MOSI_O]
set_property PACKAGE_PIN V17 [get_ports SPI0_MISO_I]
set_property PACKAGE_PIN V18 [get_ports SPI0_SCLK_O]
set_property PACKAGE_PIN R17 [get_ports SPI0_SS_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MISO_I]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MOSI_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SCLK_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SS_O]
set_property PACKAGE_PIN R19 [get_ports adc_rst]
set_property IOSTANDARD LVCMOS25 [get_ports adc_rst]
set_property PACKAGE_PIN T15 [get_ports enable]
set_property PACKAGE_PIN P18 [get_ports txnrx]

#set_property PACKAGE_PIN R16 [get_ports adc_clk_out]

set_property PACKAGE_PIN U18 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN U19 [get_ports rx_clk_in_n]
set_property PACKAGE_PIN Y16 [get_ports rx_frame_in_p]
set_property PACKAGE_PIN Y17 [get_ports rx_frame_in_n]
set_property PACKAGE_PIN U14 [get_ports tx_clk_out_p]
set_property PACKAGE_PIN U15 [get_ports tx_clk_out_n]
set_property PACKAGE_PIN V16 [get_ports tx_frame_out_p]
set_property PACKAGE_PIN W16 [get_ports tx_frame_out_n]
set_property PACKAGE_PIN Y18 [get_ports {rx_data_in_p[0]}]
set_property PACKAGE_PIN Y19 [get_ports {rx_data_in_n[0]}]
set_property PACKAGE_PIN T16 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN U17 [get_ports {rx_data_in_n[1]}]
set_property PACKAGE_PIN V20 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN W20 [get_ports {rx_data_in_n[2]}]
set_property PACKAGE_PIN T17 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN R18 [get_ports {rx_data_in_n[3]}]
set_property PACKAGE_PIN T20 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN U20 [get_ports {rx_data_in_n[4]}]
set_property PACKAGE_PIN W18 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN W19 [get_ports {rx_data_in_n[5]}]
set_property PACKAGE_PIN V15 [get_ports {tx_data_out_p[0]}]
set_property PACKAGE_PIN W15 [get_ports {tx_data_out_n[0]}]
set_property PACKAGE_PIN V12 [get_ports {tx_data_out_p[1]}]
set_property PACKAGE_PIN W13 [get_ports {tx_data_out_n[1]}]
set_property PACKAGE_PIN W14 [get_ports {tx_data_out_p[2]}]
set_property PACKAGE_PIN Y14 [get_ports {tx_data_out_n[2]}]
set_property PACKAGE_PIN T12 [get_ports {tx_data_out_p[3]}]
set_property PACKAGE_PIN U12 [get_ports {tx_data_out_n[3]}]
set_property PACKAGE_PIN T11 [get_ports {tx_data_out_p[4]}]
set_property PACKAGE_PIN T10 [get_ports {tx_data_out_n[4]}]
set_property PACKAGE_PIN U13 [get_ports {tx_data_out_p[5]}]
set_property PACKAGE_PIN V13 [get_ports {tx_data_out_n[5]}]



set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_n]
set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_p]
set_property IOSTANDARD LVCMOS25 [get_ports enable]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_p]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_n]
set_property IOSTANDARD LVCMOS25 [get_ports txnrx]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[0]}]



set_property DIFF_TERM FALSE [get_ports rx_frame_in_p]
set_property DIFF_TERM FALSE [get_ports rx_frame_in_n]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_p]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_n]


set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[0]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[5]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[4]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[3]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[2]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[1]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_p[0]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[0]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[5]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[4]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[3]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[2]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[1]}]
#set_property DIFF_TERM TRUE [get_ports {tx_data_out_n[0]}]


set_property PACKAGE_PIN R16 [get_ports adc_clk_out]
set_property IOSTANDARD LVCMOS25 [get_ports adc_clk_out]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_ad9361/adc_clk_o]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dac_data_q0[0]} {dac_data_q0[1]} {dac_data_q0[2]} {dac_data_q0[3]} {dac_data_q0[4]} {dac_data_q0[5]} {dac_data_q0[6]} {dac_data_q0[7]} {dac_data_q0[8]} {dac_data_q0[9]} {dac_data_q0[10]} {dac_data_q0[11]} {dac_data_q0[12]} {dac_data_q0[13]} {dac_data_q0[14]} {dac_data_q0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dac_data_q1[0]} {dac_data_q1[1]} {dac_data_q1[2]} {dac_data_q1[3]} {dac_data_q1[4]} {dac_data_q1[5]} {dac_data_q1[6]} {dac_data_q1[7]} {dac_data_q1[8]} {dac_data_q1[9]} {dac_data_q1[10]} {dac_data_q1[11]} {dac_data_q1[12]} {dac_data_q1[13]} {dac_data_q1[14]} {dac_data_q1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {adc_data_q0[0]} {adc_data_q0[1]} {adc_data_q0[2]} {adc_data_q0[3]} {adc_data_q0[4]} {adc_data_q0[5]} {adc_data_q0[6]} {adc_data_q0[7]} {adc_data_q0[8]} {adc_data_q0[9]} {adc_data_q0[10]} {adc_data_q0[11]} {adc_data_q0[12]} {adc_data_q0[13]} {adc_data_q0[14]} {adc_data_q0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {dac_data_i1[0]} {dac_data_i1[1]} {dac_data_i1[2]} {dac_data_i1[3]} {dac_data_i1[4]} {dac_data_i1[5]} {dac_data_i1[6]} {dac_data_i1[7]} {dac_data_i1[8]} {dac_data_i1[9]} {dac_data_i1[10]} {dac_data_i1[11]} {dac_data_i1[12]} {dac_data_i1[13]} {dac_data_i1[14]} {dac_data_i1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {adc_data_q1[0]} {adc_data_q1[1]} {adc_data_q1[2]} {adc_data_q1[3]} {adc_data_q1[4]} {adc_data_q1[5]} {adc_data_q1[6]} {adc_data_q1[7]} {adc_data_q1[8]} {adc_data_q1[9]} {adc_data_q1[10]} {adc_data_q1[11]} {adc_data_q1[12]} {adc_data_q1[13]} {adc_data_q1[14]} {adc_data_q1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {adc_data_i1[0]} {adc_data_i1[1]} {adc_data_i1[2]} {adc_data_i1[3]} {adc_data_i1[4]} {adc_data_i1[5]} {adc_data_i1[6]} {adc_data_i1[7]} {adc_data_i1[8]} {adc_data_i1[9]} {adc_data_i1[10]} {adc_data_i1[11]} {adc_data_i1[12]} {adc_data_i1[13]} {adc_data_i1[14]} {adc_data_i1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {adc_data_i0[0]} {adc_data_i0[1]} {adc_data_i0[2]} {adc_data_i0[3]} {adc_data_i0[4]} {adc_data_i0[5]} {adc_data_i0[6]} {adc_data_i0[7]} {adc_data_i0[8]} {adc_data_i0[9]} {adc_data_i0[10]} {adc_data_i0[11]} {adc_data_i0[12]} {adc_data_i0[13]} {adc_data_i0[14]} {adc_data_i0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {dac_data_i0[0]} {dac_data_i0[1]} {dac_data_i0[2]} {dac_data_i0[3]} {dac_data_i0[4]} {dac_data_i0[5]} {dac_data_i0[6]} {dac_data_i0[7]} {dac_data_i0[8]} {dac_data_i0[9]} {dac_data_i0[10]} {dac_data_i0[11]} {dac_data_i0[12]} {dac_data_i0[13]} {dac_data_i0[14]} {dac_data_i0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list adc_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list dac_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets adc_clk]
