create_clock -period 8.138 -name rx_data_clock [get_ports rx_clk_in_p]
create_clock -period 25.000 -name adc_clk_out [get_ports adc_clk_out]
#set_property SEVERITY {Warning} [get_drc_checks BIVC-1]
set_property PACKAGE_PIN P16 [get_ports SPI0_MOSI_O]
set_property PACKAGE_PIN V17 [get_ports SPI0_MISO_I]
set_property PACKAGE_PIN V18 [get_ports SPI0_SCLK_O]
set_property PACKAGE_PIN R17 [get_ports SPI0_SS_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MISO_I]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MOSI_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SCLK_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SS_O]
set_property PACKAGE_PIN R19 [get_ports adc_rst]
set_property IOSTANDARD LVCMOS25 [get_ports adc_rst]
set_property PACKAGE_PIN T15 [get_ports enable]
set_property PACKAGE_PIN P18 [get_ports txnrx]

#set_property PACKAGE_PIN R16 [get_ports adc_clk_out]

set_property PACKAGE_PIN U18 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN U19 [get_ports rx_clk_in_n]
set_property PACKAGE_PIN Y16 [get_ports rx_frame_in_p]
set_property PACKAGE_PIN Y17 [get_ports rx_frame_in_n]
set_property PACKAGE_PIN U14 [get_ports tx_clk_out_p]
set_property PACKAGE_PIN U15 [get_ports tx_clk_out_n]
set_property PACKAGE_PIN V16 [get_ports tx_frame_out_p]
set_property PACKAGE_PIN W16 [get_ports tx_frame_out_n]
set_property PACKAGE_PIN Y18 [get_ports {rx_data_in_p[0]}]
set_property PACKAGE_PIN Y19 [get_ports {rx_data_in_n[0]}]
set_property PACKAGE_PIN T16 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN U17 [get_ports {rx_data_in_n[1]}]
set_property PACKAGE_PIN V20 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN W20 [get_ports {rx_data_in_n[2]}]
set_property PACKAGE_PIN T17 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN R18 [get_ports {rx_data_in_n[3]}]
set_property PACKAGE_PIN T20 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN U20 [get_ports {rx_data_in_n[4]}]
set_property PACKAGE_PIN W18 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN W19 [get_ports {rx_data_in_n[5]}]
set_property PACKAGE_PIN V15 [get_ports {tx_data_out_p[0]}]
set_property PACKAGE_PIN W15 [get_ports {tx_data_out_n[0]}]
set_property PACKAGE_PIN V12 [get_ports {tx_data_out_p[1]}]
set_property PACKAGE_PIN W13 [get_ports {tx_data_out_n[1]}]
set_property PACKAGE_PIN W14 [get_ports {tx_data_out_p[2]}]
set_property PACKAGE_PIN Y14 [get_ports {tx_data_out_n[2]}]
set_property PACKAGE_PIN T12 [get_ports {tx_data_out_p[3]}]
set_property PACKAGE_PIN U12 [get_ports {tx_data_out_n[3]}]
set_property PACKAGE_PIN T11 [get_ports {tx_data_out_p[4]}]
set_property PACKAGE_PIN T10 [get_ports {tx_data_out_n[4]}]
set_property PACKAGE_PIN U13 [get_ports {tx_data_out_p[5]}]
set_property PACKAGE_PIN V13 [get_ports {tx_data_out_n[5]}]



set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_n]
set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_p]
set_property IOSTANDARD LVCMOS25 [get_ports enable]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_p]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_n]
set_property IOSTANDARD LVCMOS25 [get_ports txnrx]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[0]}]

set_property DIFF_TERM FALSE [get_ports rx_frame_in_p]
set_property DIFF_TERM FALSE [get_ports rx_frame_in_n]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_p]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_n]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[0]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[0]}]


set_property PACKAGE_PIN R16 [get_ports adc_clk_out]
set_property IOSTANDARD LVCMOS25 [get_ports adc_clk_out]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_ad9361/i_ad9361_lvds_ddr_io/rx_clk_o]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dac_data_r[1][0]} {dac_data_r[1][1]} {dac_data_r[1][2]} {dac_data_r[1][3]} {dac_data_r[1][4]} {dac_data_r[1][5]} {dac_data_r[1][6]} {dac_data_r[1][7]} {dac_data_r[1][8]} {dac_data_r[1][9]} {dac_data_r[1][10]} {dac_data_r[1][11]} {dac_data_r[1][12]} {dac_data_r[1][13]} {dac_data_r[1][14]} {dac_data_r[1][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dac_data_i[1][0]} {dac_data_i[1][1]} {dac_data_i[1][2]} {dac_data_i[1][3]} {dac_data_i[1][4]} {dac_data_i[1][5]} {dac_data_i[1][6]} {dac_data_i[1][7]} {dac_data_i[1][8]} {dac_data_i[1][9]} {dac_data_i[1][10]} {dac_data_i[1][11]} {dac_data_i[1][12]} {dac_data_i[1][13]} {dac_data_i[1][14]} {dac_data_i[1][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {dac_data_r[0][0]} {dac_data_r[0][1]} {dac_data_r[0][2]} {dac_data_r[0][3]} {dac_data_r[0][4]} {dac_data_r[0][5]} {dac_data_r[0][6]} {dac_data_r[0][7]} {dac_data_r[0][8]} {dac_data_r[0][9]} {dac_data_r[0][10]} {dac_data_r[0][11]} {dac_data_r[0][12]} {dac_data_r[0][13]} {dac_data_r[0][14]} {dac_data_r[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {dac_data_i[0][0]} {dac_data_i[0][1]} {dac_data_i[0][2]} {dac_data_i[0][3]} {dac_data_i[0][4]} {dac_data_i[0][5]} {dac_data_i[0][6]} {dac_data_i[0][7]} {dac_data_i[0][8]} {dac_data_i[0][9]} {dac_data_i[0][10]} {dac_data_i[0][11]} {dac_data_i[0][12]} {dac_data_i[0][13]} {dac_data_i[0][14]} {dac_data_i[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 36 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[0]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[1]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[2]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[3]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[4]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[5]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[6]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[7]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[8]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[9]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[10]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[11]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[12]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[13]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[14]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[15]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[16]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[17]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[18]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[19]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[20]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[21]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[22]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[23]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[24]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[25]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[26]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[27]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[28]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[29]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[30]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[31]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[32]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[33]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[34]} {i_axi_dma_interface/i_axi_datamover_controller/read_bytes_counter[35]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 64 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_axi_tx_mem/i_tx_mem/src_data[0]} {i_axi_tx_mem/i_tx_mem/src_data[1]} {i_axi_tx_mem/i_tx_mem/src_data[2]} {i_axi_tx_mem/i_tx_mem/src_data[3]} {i_axi_tx_mem/i_tx_mem/src_data[4]} {i_axi_tx_mem/i_tx_mem/src_data[5]} {i_axi_tx_mem/i_tx_mem/src_data[6]} {i_axi_tx_mem/i_tx_mem/src_data[7]} {i_axi_tx_mem/i_tx_mem/src_data[8]} {i_axi_tx_mem/i_tx_mem/src_data[9]} {i_axi_tx_mem/i_tx_mem/src_data[10]} {i_axi_tx_mem/i_tx_mem/src_data[11]} {i_axi_tx_mem/i_tx_mem/src_data[12]} {i_axi_tx_mem/i_tx_mem/src_data[13]} {i_axi_tx_mem/i_tx_mem/src_data[14]} {i_axi_tx_mem/i_tx_mem/src_data[15]} {i_axi_tx_mem/i_tx_mem/src_data[16]} {i_axi_tx_mem/i_tx_mem/src_data[17]} {i_axi_tx_mem/i_tx_mem/src_data[18]} {i_axi_tx_mem/i_tx_mem/src_data[19]} {i_axi_tx_mem/i_tx_mem/src_data[20]} {i_axi_tx_mem/i_tx_mem/src_data[21]} {i_axi_tx_mem/i_tx_mem/src_data[22]} {i_axi_tx_mem/i_tx_mem/src_data[23]} {i_axi_tx_mem/i_tx_mem/src_data[24]} {i_axi_tx_mem/i_tx_mem/src_data[25]} {i_axi_tx_mem/i_tx_mem/src_data[26]} {i_axi_tx_mem/i_tx_mem/src_data[27]} {i_axi_tx_mem/i_tx_mem/src_data[28]} {i_axi_tx_mem/i_tx_mem/src_data[29]} {i_axi_tx_mem/i_tx_mem/src_data[30]} {i_axi_tx_mem/i_tx_mem/src_data[31]} {i_axi_tx_mem/i_tx_mem/src_data[32]} {i_axi_tx_mem/i_tx_mem/src_data[33]} {i_axi_tx_mem/i_tx_mem/src_data[34]} {i_axi_tx_mem/i_tx_mem/src_data[35]} {i_axi_tx_mem/i_tx_mem/src_data[36]} {i_axi_tx_mem/i_tx_mem/src_data[37]} {i_axi_tx_mem/i_tx_mem/src_data[38]} {i_axi_tx_mem/i_tx_mem/src_data[39]} {i_axi_tx_mem/i_tx_mem/src_data[40]} {i_axi_tx_mem/i_tx_mem/src_data[41]} {i_axi_tx_mem/i_tx_mem/src_data[42]} {i_axi_tx_mem/i_tx_mem/src_data[43]} {i_axi_tx_mem/i_tx_mem/src_data[44]} {i_axi_tx_mem/i_tx_mem/src_data[45]} {i_axi_tx_mem/i_tx_mem/src_data[46]} {i_axi_tx_mem/i_tx_mem/src_data[47]} {i_axi_tx_mem/i_tx_mem/src_data[48]} {i_axi_tx_mem/i_tx_mem/src_data[49]} {i_axi_tx_mem/i_tx_mem/src_data[50]} {i_axi_tx_mem/i_tx_mem/src_data[51]} {i_axi_tx_mem/i_tx_mem/src_data[52]} {i_axi_tx_mem/i_tx_mem/src_data[53]} {i_axi_tx_mem/i_tx_mem/src_data[54]} {i_axi_tx_mem/i_tx_mem/src_data[55]} {i_axi_tx_mem/i_tx_mem/src_data[56]} {i_axi_tx_mem/i_tx_mem/src_data[57]} {i_axi_tx_mem/i_tx_mem/src_data[58]} {i_axi_tx_mem/i_tx_mem/src_data[59]} {i_axi_tx_mem/i_tx_mem/src_data[60]} {i_axi_tx_mem/i_tx_mem/src_data[61]} {i_axi_tx_mem/i_tx_mem/src_data[62]} {i_axi_tx_mem/i_tx_mem/src_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_axi_tx_mem/i_tx_mem/tx_mem_state_sm[0]} {i_axi_tx_mem/i_tx_mem/tx_mem_state_sm[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 15 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_axi_tx_mem/i_tx_mem/mem_addr[0]} {i_axi_tx_mem/i_tx_mem/mem_addr[1]} {i_axi_tx_mem/i_tx_mem/mem_addr[2]} {i_axi_tx_mem/i_tx_mem/mem_addr[3]} {i_axi_tx_mem/i_tx_mem/mem_addr[4]} {i_axi_tx_mem/i_tx_mem/mem_addr[5]} {i_axi_tx_mem/i_tx_mem/mem_addr[6]} {i_axi_tx_mem/i_tx_mem/mem_addr[7]} {i_axi_tx_mem/i_tx_mem/mem_addr[8]} {i_axi_tx_mem/i_tx_mem/mem_addr[9]} {i_axi_tx_mem/i_tx_mem/mem_addr[10]} {i_axi_tx_mem/i_tx_mem/mem_addr[11]} {i_axi_tx_mem/i_tx_mem/mem_addr[12]} {i_axi_tx_mem/i_tx_mem/mem_addr[13]} {i_axi_tx_mem/i_tx_mem/mem_addr[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 15 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {i_axi_tx_mem/i_tx_mem/mem_high_addr[0]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[1]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[2]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[3]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[4]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[5]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[6]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[7]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[8]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[9]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[10]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[11]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[12]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[13]} {i_axi_tx_mem/i_tx_mem/mem_high_addr[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 3 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {i_axi_dma_interface/i_axi_datamover_controller/datamover_read_sm[0]} {i_axi_dma_interface/i_axi_datamover_controller/datamover_read_sm[1]} {i_axi_dma_interface/i_axi_datamover_controller/datamover_read_sm[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 3 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {i_axi_dma_interface/i_axi_datamover_controller/datamover_write_sm[0]} {i_axi_dma_interface/i_axi_datamover_controller/datamover_write_sm[1]} {i_axi_dma_interface/i_axi_datamover_controller/datamover_write_sm[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list adc_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list dac_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list i_axi_tx_mem/i_tx_mem/dst_next]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list i_axi_tx_mem/i_tx_mem/mode]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list i_axi_tx_mem/i_tx_mem/src_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list i_axi_tx_mem/i_tx_mem/src_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets adc_clk]
