create_clock -period 8.138 -name rx_data_clock [get_ports rx_clk_in_p]
create_clock -period 25.000 -name adc_clk_out [get_ports adc_clk_out]
#set_property SEVERITY {Warning} [get_drc_checks BIVC-1]
set_property PACKAGE_PIN P16 [get_ports SPI0_MOSI_O]
set_property PACKAGE_PIN V17 [get_ports SPI0_MISO_I]
set_property PACKAGE_PIN V18 [get_ports SPI0_SCLK_O]
set_property PACKAGE_PIN R17 [get_ports SPI0_SS_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MISO_I]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_MOSI_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SCLK_O]
set_property IOSTANDARD LVCMOS25 [get_ports SPI0_SS_O]
set_property PACKAGE_PIN R19 [get_ports adc_rst]
set_property IOSTANDARD LVCMOS25 [get_ports adc_rst]
set_property PACKAGE_PIN T15 [get_ports enable]
set_property PACKAGE_PIN P18 [get_ports txnrx]

#set_property PACKAGE_PIN R16 [get_ports adc_clk_out]

set_property PACKAGE_PIN U18 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN U19 [get_ports rx_clk_in_n]
set_property PACKAGE_PIN Y16 [get_ports rx_frame_in_p]
set_property PACKAGE_PIN Y17 [get_ports rx_frame_in_n]
set_property PACKAGE_PIN U14 [get_ports tx_clk_out_p]
set_property PACKAGE_PIN U15 [get_ports tx_clk_out_n]
set_property PACKAGE_PIN V16 [get_ports tx_frame_out_p]
set_property PACKAGE_PIN W16 [get_ports tx_frame_out_n]
set_property PACKAGE_PIN Y18 [get_ports {rx_data_in_p[0]}]
set_property PACKAGE_PIN Y19 [get_ports {rx_data_in_n[0]}]
set_property PACKAGE_PIN T16 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN U17 [get_ports {rx_data_in_n[1]}]
set_property PACKAGE_PIN V20 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN W20 [get_ports {rx_data_in_n[2]}]
set_property PACKAGE_PIN T17 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN R18 [get_ports {rx_data_in_n[3]}]
set_property PACKAGE_PIN T20 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN U20 [get_ports {rx_data_in_n[4]}]
set_property PACKAGE_PIN W18 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN W19 [get_ports {rx_data_in_n[5]}]
set_property PACKAGE_PIN V15 [get_ports {tx_data_out_p[0]}]
set_property PACKAGE_PIN W15 [get_ports {tx_data_out_n[0]}]
set_property PACKAGE_PIN V12 [get_ports {tx_data_out_p[1]}]
set_property PACKAGE_PIN W13 [get_ports {tx_data_out_n[1]}]
set_property PACKAGE_PIN W14 [get_ports {tx_data_out_p[2]}]
set_property PACKAGE_PIN Y14 [get_ports {tx_data_out_n[2]}]
set_property PACKAGE_PIN T12 [get_ports {tx_data_out_p[3]}]
set_property PACKAGE_PIN U12 [get_ports {tx_data_out_n[3]}]
set_property PACKAGE_PIN T11 [get_ports {tx_data_out_p[4]}]
set_property PACKAGE_PIN T10 [get_ports {tx_data_out_n[4]}]
set_property PACKAGE_PIN U13 [get_ports {tx_data_out_p[5]}]
set_property PACKAGE_PIN V13 [get_ports {tx_data_out_n[5]}]



set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_n]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_n]
set_property IOSTANDARD LVDS_25 [get_ports rx_frame_in_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_clk_out_p]
set_property IOSTANDARD LVDS_25 [get_ports tx_frame_out_p]
set_property IOSTANDARD LVCMOS25 [get_ports enable]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_p]
set_property IOSTANDARD LVDS_25 [get_ports rx_clk_in_n]
set_property IOSTANDARD LVCMOS25 [get_ports txnrx]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {rx_data_in_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {tx_data_out_n[0]}]

set_property DIFF_TERM FALSE [get_ports rx_frame_in_p]
set_property DIFF_TERM FALSE [get_ports rx_frame_in_n]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_p]
set_property DIFF_TERM FALSE [get_ports rx_clk_in_n]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_p[0]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[5]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[4]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[3]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[2]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[1]}]
set_property DIFF_TERM FALSE [get_ports {rx_data_in_n[0]}]


set_property PACKAGE_PIN R16 [get_ports adc_clk_out]
set_property IOSTANDARD LVCMOS25 [get_ports adc_clk_out]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_ad9361/i_ad9361_lvds_ddr_io/rx_clk_o]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {g_pow_esti[1].i_power_esti/pow_i[0]} {g_pow_esti[1].i_power_esti/pow_i[1]} {g_pow_esti[1].i_power_esti/pow_i[2]} {g_pow_esti[1].i_power_esti/pow_i[3]} {g_pow_esti[1].i_power_esti/pow_i[4]} {g_pow_esti[1].i_power_esti/pow_i[5]} {g_pow_esti[1].i_power_esti/pow_i[6]} {g_pow_esti[1].i_power_esti/pow_i[7]} {g_pow_esti[1].i_power_esti/pow_i[8]} {g_pow_esti[1].i_power_esti/pow_i[9]} {g_pow_esti[1].i_power_esti/pow_i[10]} {g_pow_esti[1].i_power_esti/pow_i[11]} {g_pow_esti[1].i_power_esti/pow_i[12]} {g_pow_esti[1].i_power_esti/pow_i[13]} {g_pow_esti[1].i_power_esti/pow_i[14]} {g_pow_esti[1].i_power_esti/pow_i[15]} {g_pow_esti[1].i_power_esti/pow_i[16]} {g_pow_esti[1].i_power_esti/pow_i[17]} {g_pow_esti[1].i_power_esti/pow_i[18]} {g_pow_esti[1].i_power_esti/pow_i[19]} {g_pow_esti[1].i_power_esti/pow_i[20]} {g_pow_esti[1].i_power_esti/pow_i[21]} {g_pow_esti[1].i_power_esti/pow_i[22]} {g_pow_esti[1].i_power_esti/pow_i[23]} {g_pow_esti[1].i_power_esti/pow_i[24]} {g_pow_esti[1].i_power_esti/pow_i[25]} {g_pow_esti[1].i_power_esti/pow_i[26]} {g_pow_esti[1].i_power_esti/pow_i[27]} {g_pow_esti[1].i_power_esti/pow_i[28]} {g_pow_esti[1].i_power_esti/pow_i[29]} {g_pow_esti[1].i_power_esti/pow_i[30]} {g_pow_esti[1].i_power_esti/pow_i[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {g_pow_esti[1].i_power_esti/pow_r[0]} {g_pow_esti[1].i_power_esti/pow_r[1]} {g_pow_esti[1].i_power_esti/pow_r[2]} {g_pow_esti[1].i_power_esti/pow_r[3]} {g_pow_esti[1].i_power_esti/pow_r[4]} {g_pow_esti[1].i_power_esti/pow_r[5]} {g_pow_esti[1].i_power_esti/pow_r[6]} {g_pow_esti[1].i_power_esti/pow_r[7]} {g_pow_esti[1].i_power_esti/pow_r[8]} {g_pow_esti[1].i_power_esti/pow_r[9]} {g_pow_esti[1].i_power_esti/pow_r[10]} {g_pow_esti[1].i_power_esti/pow_r[11]} {g_pow_esti[1].i_power_esti/pow_r[12]} {g_pow_esti[1].i_power_esti/pow_r[13]} {g_pow_esti[1].i_power_esti/pow_r[14]} {g_pow_esti[1].i_power_esti/pow_r[15]} {g_pow_esti[1].i_power_esti/pow_r[16]} {g_pow_esti[1].i_power_esti/pow_r[17]} {g_pow_esti[1].i_power_esti/pow_r[18]} {g_pow_esti[1].i_power_esti/pow_r[19]} {g_pow_esti[1].i_power_esti/pow_r[20]} {g_pow_esti[1].i_power_esti/pow_r[21]} {g_pow_esti[1].i_power_esti/pow_r[22]} {g_pow_esti[1].i_power_esti/pow_r[23]} {g_pow_esti[1].i_power_esti/pow_r[24]} {g_pow_esti[1].i_power_esti/pow_r[25]} {g_pow_esti[1].i_power_esti/pow_r[26]} {g_pow_esti[1].i_power_esti/pow_r[27]} {g_pow_esti[1].i_power_esti/pow_r[28]} {g_pow_esti[1].i_power_esti/pow_r[29]} {g_pow_esti[1].i_power_esti/pow_r[30]} {g_pow_esti[1].i_power_esti/pow_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {g_pow_esti[0].i_power_esti/pow_i[0]} {g_pow_esti[0].i_power_esti/pow_i[1]} {g_pow_esti[0].i_power_esti/pow_i[2]} {g_pow_esti[0].i_power_esti/pow_i[3]} {g_pow_esti[0].i_power_esti/pow_i[4]} {g_pow_esti[0].i_power_esti/pow_i[5]} {g_pow_esti[0].i_power_esti/pow_i[6]} {g_pow_esti[0].i_power_esti/pow_i[7]} {g_pow_esti[0].i_power_esti/pow_i[8]} {g_pow_esti[0].i_power_esti/pow_i[9]} {g_pow_esti[0].i_power_esti/pow_i[10]} {g_pow_esti[0].i_power_esti/pow_i[11]} {g_pow_esti[0].i_power_esti/pow_i[12]} {g_pow_esti[0].i_power_esti/pow_i[13]} {g_pow_esti[0].i_power_esti/pow_i[14]} {g_pow_esti[0].i_power_esti/pow_i[15]} {g_pow_esti[0].i_power_esti/pow_i[16]} {g_pow_esti[0].i_power_esti/pow_i[17]} {g_pow_esti[0].i_power_esti/pow_i[18]} {g_pow_esti[0].i_power_esti/pow_i[19]} {g_pow_esti[0].i_power_esti/pow_i[20]} {g_pow_esti[0].i_power_esti/pow_i[21]} {g_pow_esti[0].i_power_esti/pow_i[22]} {g_pow_esti[0].i_power_esti/pow_i[23]} {g_pow_esti[0].i_power_esti/pow_i[24]} {g_pow_esti[0].i_power_esti/pow_i[25]} {g_pow_esti[0].i_power_esti/pow_i[26]} {g_pow_esti[0].i_power_esti/pow_i[27]} {g_pow_esti[0].i_power_esti/pow_i[28]} {g_pow_esti[0].i_power_esti/pow_i[29]} {g_pow_esti[0].i_power_esti/pow_i[30]} {g_pow_esti[0].i_power_esti/pow_i[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {g_pow_esti[0].i_power_esti/pow_r[0]} {g_pow_esti[0].i_power_esti/pow_r[1]} {g_pow_esti[0].i_power_esti/pow_r[2]} {g_pow_esti[0].i_power_esti/pow_r[3]} {g_pow_esti[0].i_power_esti/pow_r[4]} {g_pow_esti[0].i_power_esti/pow_r[5]} {g_pow_esti[0].i_power_esti/pow_r[6]} {g_pow_esti[0].i_power_esti/pow_r[7]} {g_pow_esti[0].i_power_esti/pow_r[8]} {g_pow_esti[0].i_power_esti/pow_r[9]} {g_pow_esti[0].i_power_esti/pow_r[10]} {g_pow_esti[0].i_power_esti/pow_r[11]} {g_pow_esti[0].i_power_esti/pow_r[12]} {g_pow_esti[0].i_power_esti/pow_r[13]} {g_pow_esti[0].i_power_esti/pow_r[14]} {g_pow_esti[0].i_power_esti/pow_r[15]} {g_pow_esti[0].i_power_esti/pow_r[16]} {g_pow_esti[0].i_power_esti/pow_r[17]} {g_pow_esti[0].i_power_esti/pow_r[18]} {g_pow_esti[0].i_power_esti/pow_r[19]} {g_pow_esti[0].i_power_esti/pow_r[20]} {g_pow_esti[0].i_power_esti/pow_r[21]} {g_pow_esti[0].i_power_esti/pow_r[22]} {g_pow_esti[0].i_power_esti/pow_r[23]} {g_pow_esti[0].i_power_esti/pow_r[24]} {g_pow_esti[0].i_power_esti/pow_r[25]} {g_pow_esti[0].i_power_esti/pow_r[26]} {g_pow_esti[0].i_power_esti/pow_r[27]} {g_pow_esti[0].i_power_esti/pow_r[28]} {g_pow_esti[0].i_power_esti/pow_r[29]} {g_pow_esti[0].i_power_esti/pow_r[30]} {g_pow_esti[0].i_power_esti/pow_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {data_capture_pow_thd[0]} {data_capture_pow_thd[1]} {data_capture_pow_thd[2]} {data_capture_pow_thd[3]} {data_capture_pow_thd[4]} {data_capture_pow_thd[5]} {data_capture_pow_thd[6]} {data_capture_pow_thd[7]} {data_capture_pow_thd[8]} {data_capture_pow_thd[9]} {data_capture_pow_thd[10]} {data_capture_pow_thd[11]} {data_capture_pow_thd[12]} {data_capture_pow_thd[13]} {data_capture_pow_thd[14]} {data_capture_pow_thd[15]} {data_capture_pow_thd[16]} {data_capture_pow_thd[17]} {data_capture_pow_thd[18]} {data_capture_pow_thd[19]} {data_capture_pow_thd[20]} {data_capture_pow_thd[21]} {data_capture_pow_thd[22]} {data_capture_pow_thd[23]} {data_capture_pow_thd[24]} {data_capture_pow_thd[25]} {data_capture_pow_thd[26]} {data_capture_pow_thd[27]} {data_capture_pow_thd[28]} {data_capture_pow_thd[29]} {data_capture_pow_thd[30]} {data_capture_pow_thd[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {adc_data_r[0][0]} {adc_data_r[0][1]} {adc_data_r[0][2]} {adc_data_r[0][3]} {adc_data_r[0][4]} {adc_data_r[0][5]} {adc_data_r[0][6]} {adc_data_r[0][7]} {adc_data_r[0][8]} {adc_data_r[0][9]} {adc_data_r[0][10]} {adc_data_r[0][11]} {adc_data_r[0][12]} {adc_data_r[0][13]} {adc_data_r[0][14]} {adc_data_r[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {thd_reached[0]} {thd_reached[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {smoothing_factor[0]} {smoothing_factor[1]} {smoothing_factor[2]} {smoothing_factor[3]} {smoothing_factor[4]} {smoothing_factor[5]} {smoothing_factor[6]} {smoothing_factor[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {power_esti[0][0]} {power_esti[0][1]} {power_esti[0][2]} {power_esti[0][3]} {power_esti[0][4]} {power_esti[0][5]} {power_esti[0][6]} {power_esti[0][7]} {power_esti[0][8]} {power_esti[0][9]} {power_esti[0][10]} {power_esti[0][11]} {power_esti[0][12]} {power_esti[0][13]} {power_esti[0][14]} {power_esti[0][15]} {power_esti[0][16]} {power_esti[0][17]} {power_esti[0][18]} {power_esti[0][19]} {power_esti[0][20]} {power_esti[0][21]} {power_esti[0][22]} {power_esti[0][23]} {power_esti[0][24]} {power_esti[0][25]} {power_esti[0][26]} {power_esti[0][27]} {power_esti[0][28]} {power_esti[0][29]} {power_esti[0][30]} {power_esti[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {power_esti[1][0]} {power_esti[1][1]} {power_esti[1][2]} {power_esti[1][3]} {power_esti[1][4]} {power_esti[1][5]} {power_esti[1][6]} {power_esti[1][7]} {power_esti[1][8]} {power_esti[1][9]} {power_esti[1][10]} {power_esti[1][11]} {power_esti[1][12]} {power_esti[1][13]} {power_esti[1][14]} {power_esti[1][15]} {power_esti[1][16]} {power_esti[1][17]} {power_esti[1][18]} {power_esti[1][19]} {power_esti[1][20]} {power_esti[1][21]} {power_esti[1][22]} {power_esti[1][23]} {power_esti[1][24]} {power_esti[1][25]} {power_esti[1][26]} {power_esti[1][27]} {power_esti[1][28]} {power_esti[1][29]} {power_esti[1][30]} {power_esti[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {adc_data_r[1][0]} {adc_data_r[1][1]} {adc_data_r[1][2]} {adc_data_r[1][3]} {adc_data_r[1][4]} {adc_data_r[1][5]} {adc_data_r[1][6]} {adc_data_r[1][7]} {adc_data_r[1][8]} {adc_data_r[1][9]} {adc_data_r[1][10]} {adc_data_r[1][11]} {adc_data_r[1][12]} {adc_data_r[1][13]} {adc_data_r[1][14]} {adc_data_r[1][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {adc_data_i[0][0]} {adc_data_i[0][1]} {adc_data_i[0][2]} {adc_data_i[0][3]} {adc_data_i[0][4]} {adc_data_i[0][5]} {adc_data_i[0][6]} {adc_data_i[0][7]} {adc_data_i[0][8]} {adc_data_i[0][9]} {adc_data_i[0][10]} {adc_data_i[0][11]} {adc_data_i[0][12]} {adc_data_i[0][13]} {adc_data_i[0][14]} {adc_data_i[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 16 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {adc_data_i[1][0]} {adc_data_i[1][1]} {adc_data_i[1][2]} {adc_data_i[1][3]} {adc_data_i[1][4]} {adc_data_i[1][5]} {adc_data_i[1][6]} {adc_data_i[1][7]} {adc_data_i[1][8]} {adc_data_i[1][9]} {adc_data_i[1][10]} {adc_data_i[1][11]} {adc_data_i[1][12]} {adc_data_i[1][13]} {adc_data_i[1][14]} {adc_data_i[1][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list adc_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list dac_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list power_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets adc_clk]
